storage_address: <your_storage_ip_address_or_fqdn> # Example: storage1.company.com or sds1.company.com or 10.10.10.10. For VSP One SDS Block, this can be cluster address or master node address
vault_storage_username: <your_storage_user_name>
vault_storage_secret: <your_storage_password>

secondary_storage_address: <your_storage_ip_address_or_fqdn> # Example: storage1.company.com or sds1.company.com or 10.10.10.10
vault_secondary_storage_username: <your_storage_user_name>
vault_secondary_storage_secret: <your_storage_password>